remote_theme: jekyll/minima
title: Autonomous Building Inspection Project Page
description:

repository: robora-lab/autonomous-building-inspection

navigation:
  - title: Robora Lab
    url: https://roboralab.com/index.html
  - title: GitHub
    url: https://github.com/Robora-Lab
